/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as ExpertoIntroExpertoImport } from './routes/experto/introExperto'
import { Route as ArticlesIntroArticlesImport } from './routes/articles/introArticles'
import { Route as ExpertoPostIndexImport } from './routes/experto/post/index'
import { Route as ArticlesCategoryIndexImport } from './routes/articles/category/index'
import { Route as ArticlesCategoryCategoryidIndexImport } from './routes/articles/category/$categoryid/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const ExpertoIntroExpertoRoute = ExpertoIntroExpertoImport.update({
  id: '/experto/introExperto',
  path: '/experto/introExperto',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesIntroArticlesRoute = ArticlesIntroArticlesImport.update({
  id: '/articles/introArticles',
  path: '/articles/introArticles',
  getParentRoute: () => rootRoute,
} as any)

const ExpertoPostIndexRoute = ExpertoPostIndexImport.update({
  id: '/experto/post/',
  path: '/experto/post/',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesCategoryIndexRoute = ArticlesCategoryIndexImport.update({
  id: '/articles/category/',
  path: '/articles/category/',
  getParentRoute: () => rootRoute,
} as any)

const ArticlesCategoryCategoryidIndexRoute =
  ArticlesCategoryCategoryidIndexImport.update({
    id: '/articles/category/$categoryid/',
    path: '/articles/category/$categoryid/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/articles/introArticles': {
      id: '/articles/introArticles'
      path: '/articles/introArticles'
      fullPath: '/articles/introArticles'
      preLoaderRoute: typeof ArticlesIntroArticlesImport
      parentRoute: typeof rootRoute
    }
    '/experto/introExperto': {
      id: '/experto/introExperto'
      path: '/experto/introExperto'
      fullPath: '/experto/introExperto'
      preLoaderRoute: typeof ExpertoIntroExpertoImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/articles/category/': {
      id: '/articles/category/'
      path: '/articles/category'
      fullPath: '/articles/category'
      preLoaderRoute: typeof ArticlesCategoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/experto/post/': {
      id: '/experto/post/'
      path: '/experto/post'
      fullPath: '/experto/post'
      preLoaderRoute: typeof ExpertoPostIndexImport
      parentRoute: typeof rootRoute
    }
    '/articles/category/$categoryid/': {
      id: '/articles/category/$categoryid/'
      path: '/articles/category/$categoryid'
      fullPath: '/articles/category/$categoryid'
      preLoaderRoute: typeof ArticlesCategoryCategoryidIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles/introArticles': typeof ArticlesIntroArticlesRoute
  '/experto/introExperto': typeof ExpertoIntroExpertoRoute
  '/about': typeof AboutIndexRoute
  '/articles/category': typeof ArticlesCategoryIndexRoute
  '/experto/post': typeof ExpertoPostIndexRoute
  '/articles/category/$categoryid': typeof ArticlesCategoryCategoryidIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles/introArticles': typeof ArticlesIntroArticlesRoute
  '/experto/introExperto': typeof ExpertoIntroExpertoRoute
  '/about': typeof AboutIndexRoute
  '/articles/category': typeof ArticlesCategoryIndexRoute
  '/experto/post': typeof ExpertoPostIndexRoute
  '/articles/category/$categoryid': typeof ArticlesCategoryCategoryidIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/articles/introArticles': typeof ArticlesIntroArticlesRoute
  '/experto/introExperto': typeof ExpertoIntroExpertoRoute
  '/about/': typeof AboutIndexRoute
  '/articles/category/': typeof ArticlesCategoryIndexRoute
  '/experto/post/': typeof ExpertoPostIndexRoute
  '/articles/category/$categoryid/': typeof ArticlesCategoryCategoryidIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles/introArticles'
    | '/experto/introExperto'
    | '/about'
    | '/articles/category'
    | '/experto/post'
    | '/articles/category/$categoryid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles/introArticles'
    | '/experto/introExperto'
    | '/about'
    | '/articles/category'
    | '/experto/post'
    | '/articles/category/$categoryid'
  id:
    | '__root__'
    | '/'
    | '/articles/introArticles'
    | '/experto/introExperto'
    | '/about/'
    | '/articles/category/'
    | '/experto/post/'
    | '/articles/category/$categoryid/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesIntroArticlesRoute: typeof ArticlesIntroArticlesRoute
  ExpertoIntroExpertoRoute: typeof ExpertoIntroExpertoRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ArticlesCategoryIndexRoute: typeof ArticlesCategoryIndexRoute
  ExpertoPostIndexRoute: typeof ExpertoPostIndexRoute
  ArticlesCategoryCategoryidIndexRoute: typeof ArticlesCategoryCategoryidIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesIntroArticlesRoute: ArticlesIntroArticlesRoute,
  ExpertoIntroExpertoRoute: ExpertoIntroExpertoRoute,
  AboutIndexRoute: AboutIndexRoute,
  ArticlesCategoryIndexRoute: ArticlesCategoryIndexRoute,
  ExpertoPostIndexRoute: ExpertoPostIndexRoute,
  ArticlesCategoryCategoryidIndexRoute: ArticlesCategoryCategoryidIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/articles/introArticles",
        "/experto/introExperto",
        "/about/",
        "/articles/category/",
        "/experto/post/",
        "/articles/category/$categoryid/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/articles/introArticles": {
      "filePath": "articles/introArticles.tsx"
    },
    "/experto/introExperto": {
      "filePath": "experto/introExperto.tsx"
    },
    "/about/": {
      "filePath": "about/index.tsx"
    },
    "/articles/category/": {
      "filePath": "articles/category/index.tsx"
    },
    "/experto/post/": {
      "filePath": "experto/post/index.tsx"
    },
    "/articles/category/$categoryid/": {
      "filePath": "articles/category/$categoryid/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
